version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./docker/hosts/config.conf:/etc/nginx/conf.d/config.conf
      - ./:/var/www
      - ./docker/logs:/var/log/nginx
    links:
      - php
  php:
    build: ./docker/images/php
    links:
      - db
    volumes:
      - ./:/var/www
  adminer:
    image: adminer
    ports:
      - "90:90"
    links:
      - db
  db:
    image: postgres
    ports:
    - "3306:3306"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password